version: "3.7"

services:
  test:
    image: erwinrussel/vulkanviking:hdstrangle
  environment:
    FPS: 10
    RESOLUTION: 1920x1080
    SLEEP: 0
    DISPLAY: :0
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    