version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    networks:
      - monitoring
    ports:
      - "9100:9100"
    deploy:
      mode: global

  cadvisor:
    image: google/cadvisor:latest 
    networks:
      - monitoring
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
    deploy:
      mode: global

  nvsmi-exporter:
    image: utkuozdemir/nvidia_gpu_exporter:0.3.0
    networks:
      - monitoring
    ports:
      - "9835:9835"
    devices:
      - '/dev/nvidiactl:/dev/nvidiactl'
      - '/dev/nvidia0:/dev/nvidia0'
    volumes:
      - '/usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so'
      - '/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1'
      - '/usr/bin/nvidia-smi:/usr/bin/nvidia-smi'
    deploy:
      mode: global



    