version: '3.5'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  monitoring:
    attachable: true

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    networks:
      - monitoring
    ports:
      - "9100:9100"
    deploy:
      mode: global

  cadvisor:
    image: google/cadvisor:latest 
    networks:
      - monitoring
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
    deploy:
      mode: global

  nvsmi-exporter:
    image: erwinrussel/nvsmiprom:latest 
    networks:
      - monitoring
    deploy:
      mode: global
    ports:
      - "9835:9835"
      #resources:
      #  reservations:
      #    generic_resources:
      #      - discrete_resource_spec:
      #          kind: 'NVIDIA-GPU'
      #          value: 0

  fps-collector:
    image: erwinrussel/fps_collector:latest
    networks:
      - monitoring
    deploy:
      mode: replicated
    ports:
      - "8000:8000"
      - "8001:8001"

    