global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: docker
    static_configs:
      - targets: 
        - '172.17.0.1:4999'

  - job_name: cadvisor
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: node-exporter
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: nvsmi-exporter
    dns_sd_configs:
    - names:
      - 'tasks.nvsmi-exporter'
      type: 'A'
      port: 9835

  